config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :works
  resources :artists
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :works

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :label, presence: true
  validates :country, presence: true

  scope :by_new, ->{ order(updated_at: :desc) }

  # before_save :capitalize_name
  #
  # # def capitalize_name
  # # 　self.name = self.name.capitalize
  # # end
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :artist

  validates :title, presence: true
  validates :title, uniqueness: true
  validates :release, presence: true
  validates :song, presence: true
  validates :description, presence: true

  scope :by_new, ->{ order(updated_at: :desc) }

  # before_save :capitalize_name
  #
  # def capitalize_name
  # 　self.name = self.name.capitalize
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  def index
    @artists = Artist.all.by_new 
  end

  def show
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artists_path
    else
      render 'new'
    end
  end

  def new
    @artist = Artist.new
  end

  def edit
  end

  def update
    # @work = Work.find(params[:id])
    if @artist.update(artist_params)
      redirect_to artist_path(@artist)
    else
      render 'edit'
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end


  private

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params[:artist].permit(
      :name,
      :label,
      :country,
    )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]
  def index
    @works = Work.all.by_new
  end

  def show
    # @work = Work.find(params[:id])
  end

  def create
    @work = Work.new(work_params)
    if @work.save
      redirect_to works_path
    else
      render 'new'
    end
  end

  def new
    @work = Work.new
    @work.artist_id = parmas[:artist_id] if params[:artist_id]
  end

  def edit
    # @work = Work.find(params[:id])
  end

  def update
    # @work = Work.find(params[:id])
    if @work.update(work_params)
      redirect_to work_path(@work)
    else
      render 'edit'
    end
  end

  def destroy
    # @work = Work.find(params[:id])
    @work.destroy
    redirect_to works_path
  end

  private

  def set_work
    @work = Work.find(params[:id])
  end

  def work_params
    params[:work].permit(
      :title,
      :release,
      :song,
      :description,
      :artist_id,
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/artists/_form.html.haml
=bootstrap_form_with model: @artist, local: true do |f|
  =f.text_field :name
  =f.text_field :label
  =f.text_field :country
  =f.submit

app/views/artists/edit.html.haml
= render 'form'

app/views/artists/index.html.haml
.container
  indexnnnn
  %br

.container
  -@artists.each do |artist|
    =link_to "#{artist.name}", artist_path(artist)
    %br

app/views/artists/new.html.haml
bbbbb
= render 'form'

app/views/artists/show.html.haml
.container
  aaaaa
  =@artist.name
  =@artist.label
  =@artist.country

.container
  -@artist.works.each do |work|
    =link_to "#{work.title}, #{work.release}", work_path(work)

=link_to 'back to index', artists_path
=link_to 'delete' ,artist_path(@artist), method: :delete, data: {confirm: "Are you sure you want to delete it?"}

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Soundbox
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/works/_form.html.haml
=bootstrap_form_with model: @work, local: true do |f|
  =f.text_field :title
  =f.collection_select :artist_id, Artist.all, :id, :name, include_blank: true, class: 'form-control '
  =f.text_field :release
  =f.text_field :song
  =f.text_field :description
  =f.submit 'Add new album/single', class: "btn btn-primary"

app/views/works/edit.html.haml
wwwww
= render 'form'

app/views/works/index.html.haml
.container
  %h2 Index
  %br
.container
  -@works.each do |work|
    =link_to "#{work.title}, #{work.release}, #{work.artist.name}", work_path(work)
    %br

  =link_to 'back to index', works_path

app/views/works/new.html.haml
wwwww
= render 'form'

app/views/works/show.html.haml
wwwww
.container
  %h2
    =@work.title
    =@work.release
    =@work.song
    =@work.description

.container
  =link_to 'Add New Album/Song', new_work_path
  =link_to 'back to index', works_path
  =link_to 'Edit', edit_work_path
  =link_to 'delete' ,work_path(@work), method: :delete, data: {confirm: "Are you sure you want to delete it?"}